name = "claude-proxy"
main = "src/cf-worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Optional - API Configuration
OPENAI_BASE_URL = "https://nyukitth.ap-southeast-1.clawcloudrun.com/v1"

BIG_MODEL = "gemini-2.5-pro"
MIDDLE_MODEL = "qwen-3-coder-480b"
SMALL_MODEL = "gpt-oss-120b"