name = "claude-proxy"
main = "dist/cf-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
minify = true


[vars]
# Optional - API Configuration
OPENAI_BASE_URL = "https://nyukitth.ap-southeast-1.clawcloudrun.com/v1"

BIG_MODEL = "gemini-2.5-pro"
MIDDLE_MODEL = "qwen-3-coder-480b"
SMALL_MODEL = "openai/gpt-oss-120b"

# Request limits to prevent payload too large errors
MAX_TOKENS_LIMIT = "32768"
MIN_TOKENS_LIMIT = "100"
REQUEST_TIMEOUT = "120"
MAX_RETRIES = "3"