name = "claude-proxy"
main = "dist/worker.js"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set these in Cloudflare Dashboard or using wrangler secrets)
# wrangler secret put OPENAI_BASE_URL
# wrangler secret put BIG_MODEL
# wrangler secret put MIDDLE_MODEL
# wrangler secret put SMALL_MODEL
# wrangler secret put MAX_TOKENS_LIMIT
# wrangler secret put REQUEST_TIMEOUT

[vars]
OPENAI_BASE_URL="https://nyukitth.ap-southeast-1.clawcloudrun.com/v1"
BIG_MODEL="gemini-2.5-pro"
MIDDLE_MODEL="qwen-3-coder-480b"
SMALL_MODEL="openai/gpt-oss-120b"
LOG_LEVEL = "WARNING"

# Build configuration
[build]
command = "npm run build:worker"
